services:
  uxo:
    image: ghcr.io/0-5788719150923125/uxo:latest
    build:
      context: .
    ipc: host
    network_mode: host
    volumes:
      - ./src:/src
    environment:
      LOGURU_LEVEL: DEBUG
    env_file:
      - .env