version: '3.9'

services:
  uxo:
    image: ghcr.io/0-5788719150923125/uxo:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./src:/src
    environment:
      LOGURU_LEVEL: DEBUG
    env_file:
      - .env